// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Echarts: typeof import('./components/echarts.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    EnProcess: typeof import('./components/EnProcess.md')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    ZhProcess: typeof import('./components/ZhProcess.md')['default']
  }
}

export { }
